export const ROLES = {
  ADMIN: "ADMIN",
  HR: "HR",
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const USER_QUOTAS = {
  MAX_ADMIN: 1,
  MAX_ACTIVE_HR: 5,
} as const;

export const PERMISSIONS = {
  EMPLOYEE_READ: "employee:read",
  EMPLOYEE_CREATE: "employee:create",
  EMPLOYEE_UPDATE: "employee:update",
  EMPLOYEE_DELETE: "employee:delete",
  DOCUMENT_READ: "document:read",
  DOCUMENT_UPLOAD: "document:upload",
  DOCUMENT_DELETE: "document:delete",
  AUDIT_READ: "audit:read",
  USER_MANAGE: "user:manage",
  MASTER_MANAGE: "master:manage",
  TRANSPORT_READ: "transport:read",
  TRANSPORT_MANAGE: "transport:manage",
  SALARY_READ: "salary:read",
  SALARY_MANAGE: "salary:manage",
  PAYROLL_READ: "payroll:read",
  PAYROLL_MANAGE: "payroll:manage",
  PAYROLL_APPROVE: "payroll:approve",
  GRATUITY_READ: "gratuity:read",
  GRATUITY_MANAGE: "gratuity:manage",
  PAYSLIP_READ: "payslip:read",
  PAYSLIP_MANAGE: "payslip:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.MASTER_MANAGE,
    PERMISSIONS.TRANSPORT_READ,
    PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.GRATUITY_READ,
    PERMISSIONS.GRATUITY_MANAGE,
    PERMISSIONS.PAYSLIP_READ,
    PERMISSIONS.PAYSLIP_MANAGE,
  ],
  [ROLES.HR]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.TRANSPORT_READ,
    PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.GRATUITY_READ,
    PERMISSIONS.GRATUITY_MANAGE,
    PERMISSIONS.PAYSLIP_READ,
    PERMISSIONS.PAYSLIP_MANAGE,
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  return Boolean(permissions && permissions.includes(permission));
}
